### ISSUE TITLE
test ways to move pieces

### ISSUE THREAD

**Issue by jwinfield27** [jwinfield27/ChessAyeEye#6]
currently hope to operate this functionality from controller but we will see what happens.

**Comment by wallaby5716** [comment]
Ive added some utility stuff in Cheese which is where our player will be moving things.

We should probably just start moving them manually just to figure out swapping pieces to different squares etc.

**Comment by wallaby5716** [comment]
also you should collapse everything in Cheese except:
panelChessboard*
coordToSquare
squareToCoord
Paint and
Cheese

the rest is auto -enerated so don't touch that shit please for the love of god
